name = "seer-network"

# This is the exact field Cloudflare Pages looks for
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "NETWORK_STATE"

[[d1_databases]]
binding = "SEER_DB"
database_name = "seer_nodes"
