//! # Seer Transaction Model
//!
//! Defines the transaction structure used in the Seer network. Transactions
//! are the atomic unit of state change: they transfer tokens between accounts,
//! burn fees, and carry optional BoC payloads for smart-contract interactions.
//!
//! ## Transaction Lifecycle
//! 1. **Construction** — sender builds a `Transaction` with inputs/outputs.
//! 2. **Signing** — sender signs the transaction hash with their private key.
//! 3. **Validation** — nodes verify signature, balance sufficiency, and fee.
//! 4. **Inclusion** — valid transactions are included in a block.
//! 5. **Execution** — ledger applies state changes.

use std::collections::HashSet;

// ─── SHA-256 (inlined) ────────────────────────────────────────────────────────

fn sha256(data: &[u8]) -> [u8; 32] {
    const K: [u32; 64] = [
        0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,
        0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,
        0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,
        0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,
        0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,
        0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,
        0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,
        0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2,
    ];
    let mut h: [u32; 8] = [
        0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,
        0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19,
    ];
    let bit_len = (data.len() as u64).wrapping_mul(8);
    let mut msg = data.to_vec();
    msg.push(0x80);
    while (msg.len() % 64) != 56 { msg.push(0x00); }
    msg.extend_from_slice(&bit_len.to_be_bytes());
    for chunk in msg.chunks(64) {
        let mut w = [0u32; 64];
        for i in 0..16 {
            w[i] = u32::from_be_bytes([chunk[i*4],chunk[i*4+1],chunk[i*4+2],chunk[i*4+3]]);
        }
        for i in 16..64 {
            let s0 = w[i-15].rotate_right(7)^w[i-15].rotate_right(18)^(w[i-15]>>3);
            let s1 = w[i-2].rotate_right(17)^w[i-2].rotate_right(19)^(w[i-2]>>10);
            w[i] = w[i-16].wrapping_add(s0).wrapping_add(w[i-7]).wrapping_add(s1);
        }
        let [mut a,mut b,mut c,mut d,mut e,mut f,mut g,mut hh] =
            [h[0],h[1],h[2],h[3],h[4],h[5],h[6],h[7]];
        for i in 0..64 {
            let s1 = e.rotate_right(6)^e.rotate_right(11)^e.rotate_right(25);
            let ch = (e&f)^((!e)&g);
            let t1 = hh.wrapping_add(s1).wrapping_add(ch).wrapping_add(K[i]).wrapping_add(w[i]);
            let s0 = a.rotate_right(2)^a.rotate_right(13)^a.rotate_right(22);
            let maj = (a&b)^(a&c)^(b&c);
            let t2 = s0.wrapping_add(maj);
            hh=g; g=f; f=e; e=d.wrapping_add(t1); d=c; c=b; b=a; a=t1.wrapping_add(t2);
        }
        h[0]=h[0].wrapping_add(a); h[1]=h[1].wrapping_add(b);
        h[2]=h[2].wrapping_add(c); h[3]=h[3].wrapping_add(d);
        h[4]=h[4].wrapping_add(e); h[5]=h[5].wrapping_add(f);
        h[6]=h[6].wrapping_add(g); h[7]=h[7].wrapping_add(hh);
    }
    let mut out = [0u8; 32];
    for (i,&word) in h.iter().enumerate() {
        out[i*4..(i+1)*4].copy_from_slice(&word.to_be_bytes());
    }
    out
}

// ─── Address ──────────────────────────────────────────────────────────────────

/// A 32-byte account address (derived from ADNL identity or public key hash).
pub type Address = [u8; 32];

// ─── Transaction types ────────────────────────────────────────────────────────

/// The kind of transaction.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TxKind {
    /// Simple token transfer.
    Transfer,
    /// Coinbase / block reward (no sender).
    Coinbase,
    /// Fee burn transaction (generated by the protocol).
    Burn,
    /// Smart-contract invocation carrying a BoC payload.
    ContractCall { payload_hash: [u8; 32] },
}

// ─── Transaction ──────────────────────────────────────────────────────────────

/// A Seer network transaction.
#[derive(Debug, Clone)]
pub struct Transaction {
    /// Sender address (all-zero for coinbase).
    pub sender: Address,
    /// Recipient address.
    pub recipient: Address,
    /// Amount transferred in base units.
    pub amount: u64,
    /// Transaction fee in base units.
    pub fee: u64,
    /// Amount burned from the fee.
    pub burned: u64,
    /// Monotonically increasing nonce for replay protection.
    pub nonce: u64,
    /// Unix timestamp.
    pub timestamp: u64,
    /// Transaction kind.
    pub kind: TxKind,
    /// 32-byte HMAC-SHA256 signature (stand-in for Ed25519).
    pub signature: [u8; 32],
    /// Cached transaction hash.
    hash: [u8; 32],
}

impl Transaction {
    /// Creates a new unsigned transaction and computes its hash.
    pub fn new(
        sender: Address,
        recipient: Address,
        amount: u64,
        fee: u64,
        burned: u64,
        nonce: u64,
        timestamp: u64,
        kind: TxKind,
    ) -> Self {
        let mut tx = Transaction {
            sender,
            recipient,
            amount,
            fee,
            burned,
            nonce,
            timestamp,
            kind,
            signature: [0u8; 32],
            hash: [0u8; 32],
        };
        tx.hash = tx.compute_hash();
        tx
    }

    /// Creates a coinbase transaction (block reward to miner).
    pub fn coinbase(recipient: Address, reward: u64, height: u64) -> Self {
        Transaction::new(
            [0u8; 32],
            recipient,
            reward,
            0,
            0,
            height, // nonce = block height for coinbase
            0,
            TxKind::Coinbase,
        )
    }

    /// Computes the canonical transaction hash (excluding the signature field).
    fn compute_hash(&self) -> [u8; 32] {
        let mut buf = Vec::with_capacity(32 + 32 + 8 + 8 + 8 + 8 + 8 + 1);
        buf.extend_from_slice(&self.sender);
        buf.extend_from_slice(&self.recipient);
        buf.extend_from_slice(&self.amount.to_le_bytes());
        buf.extend_from_slice(&self.fee.to_le_bytes());
        buf.extend_from_slice(&self.burned.to_le_bytes());
        buf.extend_from_slice(&self.nonce.to_le_bytes());
        buf.extend_from_slice(&self.timestamp.to_le_bytes());
        // Encode kind discriminant.
        match &self.kind {
            TxKind::Transfer => buf.push(0),
            TxKind::Coinbase => buf.push(1),
            TxKind::Burn => buf.push(2),
            TxKind::ContractCall { payload_hash } => {
                buf.push(3);
                buf.extend_from_slice(payload_hash);
            }
        }
        sha256(&buf)
    }

    /// Returns the transaction hash.
    pub fn hash(&self) -> &[u8; 32] {
        &self.hash
    }

    /// Attaches a signature to the transaction.
    pub fn set_signature(&mut self, sig: [u8; 32]) {
        self.signature = sig;
    }

    /// Returns `true` if this is a coinbase transaction.
    pub fn is_coinbase(&self) -> bool {
        self.kind == TxKind::Coinbase
    }

    /// Returns the total cost to the sender (amount + fee).
    pub fn total_cost(&self) -> u64 {
        self.amount.saturating_add(self.fee)
    }
}

// ─── Transaction validation ───────────────────────────────────────────────────

/// Errors from transaction validation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TxError {
    /// Sender has insufficient balance.
    InsufficientBalance { available: u64, required: u64 },
    /// Fee is below the minimum.
    FeeTooLow { provided: u64, minimum: u64 },
    /// The transaction has already been seen (replay).
    Replay,
    /// Signature is missing (all-zero).
    MissingSignature,
    /// Coinbase transaction has a non-zero sender.
    InvalidCoinbase,
    /// Amount is zero.
    ZeroAmount,
}

impl std::fmt::Display for TxError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            TxError::InsufficientBalance { available, required } =>
                write!(f, "insufficient balance: have {available}, need {required}"),
            TxError::FeeTooLow { provided, minimum } =>
                write!(f, "fee too low: provided {provided}, minimum {minimum}"),
            TxError::Replay => write!(f, "transaction replay detected"),
            TxError::MissingSignature => write!(f, "transaction has no signature"),
            TxError::InvalidCoinbase => write!(f, "coinbase has non-zero sender"),
            TxError::ZeroAmount => write!(f, "transaction amount is zero"),
        }
    }
}

/// Minimum transaction fee (1000 base units = 0.00001 SEER).
pub const MIN_TX_FEE: u64 = 1_000;

/// Validates a transaction against a sender balance and a seen-nonce set.
///
/// `sender_balance` is the current confirmed balance of the sender.
/// `seen_nonces` tracks nonces already used by this sender.
pub fn validate_tx(
    tx: &Transaction,
    sender_balance: u64,
    seen_nonces: &HashSet<u64>,
) -> Result<(), TxError> {
    // Coinbase validation.
    if tx.is_coinbase() {
        if tx.sender != [0u8; 32] {
            return Err(TxError::InvalidCoinbase);
        }
        return Ok(());
    }

    // Zero amount guard.
    if tx.amount == 0 {
        return Err(TxError::ZeroAmount);
    }

    // Signature check.
    if tx.signature == [0u8; 32] {
        return Err(TxError::MissingSignature);
    }

    // Fee check.
    if tx.fee < MIN_TX_FEE {
        return Err(TxError::FeeTooLow { provided: tx.fee, minimum: MIN_TX_FEE });
    }

    // Replay check.
    if seen_nonces.contains(&tx.nonce) {
        return Err(TxError::Replay);
    }

    // Balance check.
    let required = tx.total_cost();
    if sender_balance < required {
        return Err(TxError::InsufficientBalance { available: sender_balance, required });
    }

    Ok(())
}

// ─── Transaction pool ─────────────────────────────────────────────────────────

/// An in-memory pool of pending (unconfirmed) transactions.
///
/// Transactions are stored by hash and ordered by fee (highest first) for
/// block inclusion priority.
#[derive(Debug, Default)]
pub struct TxPool {
    txs: std::collections::HashMap<[u8; 32], Transaction>,
}

impl TxPool {
    /// Creates a new, empty pool.
    pub fn new() -> Self {
        Self::default()
    }

    /// Adds a transaction to the pool.
    ///
    /// Duplicate hashes are silently ignored.
    pub fn add(&mut self, tx: Transaction) {
        self.txs.insert(*tx.hash(), tx);
    }

    /// Removes a transaction by hash.
    pub fn remove(&mut self, hash: &[u8; 32]) {
        self.txs.remove(hash);
    }

    /// Returns transactions sorted by fee descending (for block building).
    pub fn sorted_by_fee(&self) -> Vec<&Transaction> {
        let mut txs: Vec<&Transaction> = self.txs.values().collect();
        txs.sort_unstable_by(|a, b| b.fee.cmp(&a.fee));
        txs
    }

    /// Returns the number of pending transactions.
    pub fn len(&self) -> usize {
        self.txs.len()
    }

    /// Returns `true` if the pool is empty.
    pub fn is_empty(&self) -> bool {
        self.txs.is_empty()
    }

    /// Returns `true` if the pool contains a transaction with the given hash.
    pub fn contains(&self, hash: &[u8; 32]) -> bool {
        self.txs.contains_key(hash)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_tx(amount: u64, fee: u64, nonce: u64) -> Transaction {
        let mut tx = Transaction::new(
            [1u8; 32], [2u8; 32], amount, fee, fee / 100,
            nonce, 1_700_000_000, TxKind::Transfer,
        );
        tx.set_signature([0xABu8; 32]);
        tx
    }

    #[test]
    fn test_tx_hash_deterministic() {
        let t1 = make_tx(1_000, 1_000, 0);
        let t2 = make_tx(1_000, 1_000, 0);
        assert_eq!(t1.hash(), t2.hash());
    }

    #[test]
    fn test_tx_different_nonce_different_hash() {
        let t1 = make_tx(1_000, 1_000, 0);
        let t2 = make_tx(1_000, 1_000, 1);
        assert_ne!(t1.hash(), t2.hash());
    }

    #[test]
    fn test_coinbase_valid() {
        let cb = Transaction::coinbase([3u8; 32], 5_000_000_000, 0);
        assert!(validate_tx(&cb, 0, &HashSet::new()).is_ok());
    }

    #[test]
    fn test_validate_ok() {
        let tx = make_tx(10_000, 1_000, 0);
        assert!(validate_tx(&tx, 100_000, &HashSet::new()).is_ok());
    }

    #[test]
    fn test_validate_insufficient_balance() {
        let tx = make_tx(10_000, 1_000, 0);
        let err = validate_tx(&tx, 5_000, &HashSet::new()).unwrap_err();
        assert!(matches!(err, TxError::InsufficientBalance { .. }));
    }

    #[test]
    fn test_validate_fee_too_low() {
        let tx = make_tx(10_000, 1, 0); // fee = 1, below MIN_TX_FEE
        let err = validate_tx(&tx, 100_000, &HashSet::new()).unwrap_err();
        assert!(matches!(err, TxError::FeeTooLow { .. }));
    }

    #[test]
    fn test_validate_replay() {
        let tx = make_tx(10_000, 1_000, 5);
        let mut seen = HashSet::new();
        seen.insert(5u64);
        let err = validate_tx(&tx, 100_000, &seen).unwrap_err();
        assert_eq!(err, TxError::Replay);
    }

    #[test]
    fn test_validate_missing_signature() {
        let tx = Transaction::new(
            [1u8; 32], [2u8; 32], 10_000, 1_000, 10,
            0, 1_700_000_000, TxKind::Transfer,
        ); // no signature set
        let err = validate_tx(&tx, 100_000, &HashSet::new()).unwrap_err();
        assert_eq!(err, TxError::MissingSignature);
    }

    #[test]
    fn test_validate_zero_amount() {
        let mut tx = Transaction::new(
            [1u8; 32], [2u8; 32], 0, 1_000, 10,
            0, 1_700_000_000, TxKind::Transfer,
        );
        tx.set_signature([0xABu8; 32]);
        let err = validate_tx(&tx, 100_000, &HashSet::new()).unwrap_err();
        assert_eq!(err, TxError::ZeroAmount);
    }

    #[test]
    fn test_tx_pool_sorted_by_fee() {
        let mut pool = TxPool::new();
        pool.add(make_tx(1_000, 2_000, 0));
        pool.add(make_tx(1_000, 5_000, 1));
        pool.add(make_tx(1_000, 1_000, 2));
        let sorted = pool.sorted_by_fee();
        assert_eq!(sorted[0].fee, 5_000);
        assert_eq!(sorted[2].fee, 1_000);
    }

    #[test]
    fn test_tx_pool_remove() {
        let mut pool = TxPool::new();
        let tx = make_tx(1_000, 1_000, 0);
        let hash = *tx.hash();
        pool.add(tx);
        assert!(pool.contains(&hash));
        pool.remove(&hash);
        assert!(!pool.contains(&hash));
    }
}
